### ISSUE TITLE
package install fails on mac

### ISSUE THREAD

**Issue by colinr23** [am2222/nzdggs#4]
Downloading GitHub repo am2222/nzdggs@master
from URL https://api.github.com/repos/am2222/nzdggs/zipball/master
Installing nzdggs
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/ms/1g6n66qn0jx2dvss7cwh431c0000gn/T/RtmpT8IjZP/devtools20233cbd308/am2222-nzdggs-cf15b87'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘nzdggs’ ...
** R
** preparing package for lazy loading
Warning: package ‘R6’ was built under R version 3.4.4
Warning: package ‘dplyr’ was built under R version 3.4.4
Warning: package ‘rgdal’ was built under R version 3.4.4
Warning: package ‘sp’ was built under R version 3.4.4
Warning: package ‘raster’ was built under R version 3.4.4
Warning: package ‘rgeos’ was built under R version 3.4.4
Warning: package ‘dggridR’ was built under R version 3.4.4
Warning: package ‘stringr’ was built under R version 3.4.4
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in load(name, envir = .GlobalEnv) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
Calls: sys.load.image -> load
In addition: Warning message:
file ‘.RData’ has magic number 'RDX3'
  Use of save versions prior to 2 is deprecated 
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/nzdggs’
Installation failed: Command failed (1)

**Comment by am2222** [comment]
@colinr23 
I think the issue was with `.Rdata` file which was cached and `.gitignore` did not remove it. it must work now by this commit. https://github.com/am2222/nzdggs/commit/8d4c7875149a736c186983d743700109a44c68b5
